server:
  port: 8080
  servlet:
    context-path: /webchat-server #  context path

# DataSource
spring:
  datasource:
    name: webchat-server
    type: com.alibaba.druid.pool.DruidDataSource # use Druid
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/im_bird?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    min-evictable-time-millis: 300000
    validation-query: SELECT 'x
    test-while-idle: true
    test-on-borrow: false

# mapper locations
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.17.9.194:22122
